---
# Fail if not Windows
- name: Fail if not Windows
  ansible.builtin.fail:
    msg: "Winlogbeat is specifically designed for Windows"
  when: ansible_system != 'Win32NT'

# Import variables
- name: Gather OS system specific variables
  action: ansible.builtin.include_vars
  args:
    file: "{{ lookup('first_found',
              [ansible_system ~ '.yml', 'default.yml'],
              paths=[role_path ~ '/vars']) }}"

- name: Gather Distribution specific variables
  action: ansible.builtin.include_vars
  args:
    file: "{{ lookup('first_found',
              [
                ansible_system ~ '-' ~ ansible_os_family ~ '-' ~ ansible_distribution ~ '-' ~ ansible_distribution_version ~ '.yml',
                ansible_system ~ '-' ~ ansible_os_family ~ '-' ~ ansible_distribution ~ '-' ~ ansible_distribution_major_version ~ '.yml',
                ansible_system ~ '-' ~ ansible_os_family ~ '-' ~ ansible_distribution ~ '.yml',
                ansible_system ~ '-' ~ ansible_os_family ~ '.yml',
                'default.yml'
              ],
              paths=[role_path ~ '/vars']) }}"

# Install
- name: Install Winlogbeat
  ansible.builtin.include_tasks: install.yml
  tags: ['install']

# Configure
- name: Configure Winlogbeat
  ansible.builtin.include_tasks: configure.yml
  tags: ['configure']

# Manage service
- name: Manage Winlogbeat service
  ansible.builtin.include_tasks: service.yml
  tags: ['service']
